---

jobs:
  include:
    - stage: Build

      language: go
      go: 1.13
      services:
        - docker
      script:
        - make
        - git diff -- *.go && git diff --quiet -- *.go
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - curl -q -sSL --max-time 10 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "release"
        - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
        - DOCKER_IMAGE="${DOCKER_USER}/$(make name)" IMAGE_VERSION="$(make version)" ./scripts/release build
        - DOCKER_IMAGE="${DOCKER_USER}/$(make name)" IMAGE_VERSION="$(make version)-light" DOCKERFILE=Dockerfile_light ./scripts/release build

    - stage: Publish

      language: minimal
      script:
        - curl -q -sSL --max-time 10 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "docker_promote"
        - scripts/docker_promote "${DOCKER_USER}/$(make name)" "$(make version)"
        - scripts/docker_promote "${DOCKER_USER}/$(make name)" "$(make version)-light" "light"
      after_success:
        - curl -q -sSL --max-time 10 -X POST https://goreportcard.com/checks?repo=github.com/${TRAVIS_REPO_SLUG}

stages:
  - Build
  - name: Publish
    if: branch = master && type = push

notifications:
  email: false
