jobs:
  include:
  - stage: Build

    sudo: required
    services:
    - docker
    script: make
    after_success: |
      echo ${DOCKER_PASS} | docker login -u vibioh --password-stdin
      docker push vibioh/`make name`:`make version`

  - stage: Publish

    sudo: required
    services:
    - docker
    script: |
      echo ${DOCKER_PASS} | docker login -u vibioh --password-stdin
      docker pull vibioh/`make name`:`make version`
      docker tag vibioh/`make name`:`make version` vibioh/`make name`:latest
      docker push vibioh/`make name`:latest
    after_success: |
      curl -s -X POST https://goreportcard.com/checks?repo=github.com/ViBiOh/viws

stages:
  - Build
  - name: Publish
    if: branch = master

notifications:
  email: false
