language: go
sudo: required
services:
- docker
go:
- 1.7
install: make
script: |
  docker build -t ${DOCKER_USER}/http .
after_success: |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} && docker push ${DOCKER_USER}/http
  fi
notifications:
  email: false
